config/routes.rb
CovDemo::Application.routes.draw do

  
  root :to  => 'user_sessions#default'
  match 'activate/(:activation_code)' => 'users#activate', :as => :activate_account
  match 'send_activation(/:user_id)' => 'users#send_activation', :as => :send_activation
  
  match 'forgot_password' => 'user_sessions#forgot_password', :as => :forgot_password, :via => :get
  match 'forgot_password' => 'user_sessions#forgot_password_lookup_email', :as => :forgot_password, :via => :post
  
  put 'reset_password/:reset_password_code' => 'users#reset_password_submit', :as => :reset_password, :via => :put
  get 'reset_password/:reset_password_code' => 'users#reset_password', :as => :reset_password, :via => :get
  
  default_url_options :host => "localhost:3000"
  match 'login' => "user_sessions#new",       :as => :login
  match 'logout' => "user_sessions#destroy",  :as => :logout

  
  resources :user_sessions
  resources :users
  resource :user, :as => "account"
  match 'admin' => "users#index"
  
  match 'signup' => 'users#new', :as => :signup

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :users
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :group
  accepts_nested_attributes_for :group
  
  def group_name
    Group.find(self.group_id).name
  end
  
  def active?
    active
  end
  
  def admin?
    is_admin
  end
  
  def activate!
    self.active = true
    save
  end
  
  def deactivate!
    self.active = false
    save
  end
  
  def send_activation_instructions!
    reset_perishable_token!
    Notifier.activation_instructions(self).deliver
  end
  
  def send_activation_confirmation!
    reset_perishable_token!
    Notifier.activation_confirmation(self).deliver
  end
  
  def send_forgot_password!
    reset_perishable_token!
    Notifier.forgot_password(self).deliver
  end
  
  def make_admin!
    self.is_admin = true
    save
  end
  
  def remove_admin!
    self.is_admin = false
    save
  end
  
  acts_as_authentic do |c|
    c.merge_validates_length_of_password_field_options({:minimum => 8})
    end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  generalize_credentials_error_messages true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  filter_parameter_logging :password, :password_confirmation # there are underscores :-|
  helper_method :current_user_session, :current_user

  private
    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end

    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.user
    end

    def require_user
      unless current_user
        store_location
        flash[:notice] = "You must be logged in to access this page"
        redirect_to new_user_session_url
        return false
      end
    end

    def require_no_user
      if current_user
        store_location
        flash[:notice] = "You must be logged out to access this page"
        redirect_to account_url
        return false
      end
    end
    
    def require_admin
      unless current_user.admin?
        store_location
        flash[:notice] = "You must be an Admin to access this page"
        redirect_to account_url
        return false
      end
    end
    

    def store_location
      session[:return_to] = request.request_uri
    end

    def redirect_back_or_default(default)
      redirect_to(session[:return_to] || default)
      session[:return_to] = nil
    end
end

        
          

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => :destroy
  
  def new
    @user_session = UserSession.new
  end
  
  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Login successful!"
      redirect_back_or_default account_url(@current_user)
    else
      render :action => :new
    end
  end
  
  def default
    if current_user
      redirect_to account_url
    else
      redirect_to new_user_session_url
    end
  end
  
  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_back_or_default new_user_session_url
  end
  
  def forgot_password
    if current_user
      redirect_to edit_account_url
    else
      @user_session = UserSession.new()
    end
  end
  
  def forgot_password_lookup_email
    if current_user
      redirect_to edit_account_url
    else
      user = User.find_by_email(params[:user_session][:email])
      if user
        user.send_forgot_password!
        flash[:notice] = "A link to reset your password has been emailed to you."
      else
        flash.now[:error] = "Email #{params[:user_session][:email]} wasn't found."
        render :action => :forgot_password
      end
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => [:show, :edit, :update]
  before_filter :load_user_using_perishable_token, :only => [:reset_password, :reset_password_submit]
  before_filter :require_admin, :only => [:index]
  
  def new
    @user = User.new
    @user.group = Group.new
  end
  
  def create
    @user = User.new(params[:user])
    
    @user.group = Group.find_or_create_by_name(params[:user][:group_attributes][:name])
    
    
    if @user.save_without_session_maintenance
      @user.send_activation_instructions!
      flash[:notice] = "Thank you for registering! You will receive activation instructions in your email."
      redirect_to signup_url
    else
      flash.now[:error] = "There was a problem creating your account."
      render :action => :new
    end
  end
  
  
  def activate
    @user = User.find_using_perishable_token(params[:activation_code], 1.week)
  
    if @user.activate!
      UserSession.create(@user, false)
      @user.send_activation_confirmation!
      redirect_to account_url
    else
      render :action  => :new
    end
  end
  
  def show
    @user = @current_user
  end
  
  def index
    @users = User.find(:all, :order => :name)
  end
  
  def update
    @user = @current_user
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated!"
      redirect_to account_url
    else
      render :action => edit
    end
  end
  
  
  def reset_password
    @user = User.find_using_perishable_token(params[:reset_password_code], 1.week)
    
    render
  end
  
  def reset_password_submit
    @user = User.find_using_perishable_token(params[:reset_password_code], 1.week)
    
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.save
      flash[:notice] = "Password successfully updated."
      redirect_to account_url
    else
      render :action => :edit
    end
  end
  
  private
  def load_user_using_perishable_token
    @user = User.find_using_perishable_token(params[:reset_password_code], 1.week)
    unless @user
      flash[:notice] = "Sorry, we could not locate your account."
      redirect_to login_url
    end
  end
  
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CovDemo</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<%= render "shared/notice_messages" %>
<%= yield %>

</body>
</html>

app/views/notifier/activation_confirmation.erb
Your account has been activated! Follow the link to login:

<%= login_url %>

app/views/notifier/activation_instructions.erb
Thank you for registering! Please click the link below to confirm your email account. An administrator will review your registration and activate your account. You will receive an email notification when your account has been activated.

<%= @account_activation_url %>

app/views/notifier/forgot_password.erb
A request to reset your password has been made.  
If you did not make this request, simply ignore this email.  
If you did make this request just click the link below:  
<%= @reset_password_url %>
If the above URL does not work try copying and pasting it into your browser.  
If you continue to have problem please feel free to contact us.

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
<div id="val_error" >
	<p style= "float:right;"> <%= link_to_function 'X', "Effect.Fade('val_error')" %></p>
		<ul>
<% target.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>	
<% end %>
</ul>
</div>
<% end %>

app/views/shared/_notice_messages.html.erb
<% if flash.any? %>
<% flash.each do |key, msg| %>
<div id="<%= key %>" >
	<p style= "float:right;"> <%= link_to_function 'X', "Effect.Fade('#{key}')" %></p>
	<p><%= msg %></p>
	<div class="clear"></div>
</div>
<% end %>
<% end %>

app/views/user_sessions/forgot_password.html.erb
<h1>Forgot Password</h1>
<p>
Please enter the email address you used to register.
</p>
<%= form_for @user_session, :as => :user_session, :url => forgot_password_url do |f| %>
  <%= f.label :email %><br />
  <%= f.text_field :email %><br />
  <br />
  <%= f.submit "Send Password Reset Link" %>
<% end %>

app/views/user_sessions/forgot_password_lookup_email.html.erb
<h1>Forgot Password</h1>
<p> :D </p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<% form_for @user_session, :as => :user_session, :url => { :action => "create" } do |f| %>
  <%= render "shared/error_messages", :target => @user_session %>
  <%= f.label :email %><br />
  <%= f.text_field :email %><br />
  <br />
  <%= f.label :password %><br />
  <%= f.password_field :password %><br />
  <br />
  <%= f.check_box :remember_me %><%= f.label :remember_me %><br />
  <br />
  <%= f.submit "Login" %>
<br/>
  <%= link_to "Forgot Password?", forgot_password_path %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit My Account</h1>

<% form_for @user, :url => account_path do |f| %>
  <%= render :partial => "form", :object => f, :locals => { :user => @user } %>
  <%= f.submit "Update" %>
<% end %>

<br /><%= link_to "My Profile", account_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
	<th>Group</th>
    <th>Active?</th>
    <th>Admin?</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%=h user.name %></td>
    <td><%=h user.email %></td>
	<td><%=h user.group.name %></td>
	<td><%=h user.active? %></td>
    <td><%=h user.is_admin %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/users/new.html.erb
<h1>Register</h1>
<%= render "shared/error_messages", :target => @user %>

<%= form_for @user do |user_form| %>
  <p>
  <%= user_form.label :name %><br />
  <%= user_form.text_field :name %>
</p>
<p>
  <%= user_form.label :email %><br />
  <%= user_form.text_field :email %>
</p>

  <%= user_form.fields_for :group do |group_form| %>
    Group <%= group_form.label :name %><br/ >
    <%= group_form.text_field :name %>
  <% end %>

<p>
  <%= user_form.label :password %><br />
  <%= user_form.password_field :password %>
</p>
<p>
  <%= user_form.label :password_confirmation %><br />
  <%= user_form.password_field :password_confirmation %>
</p>



  <%= user_form.submit "Register" %>
<% end %>

app/views/users/reset_password.html.erb
<h1>Reset your Password:</h1>
<%= form_for @user, :url => reset_password_url do |f| %>
<p>
	<%= f.label :password %>
</br>
	<%= f.password_field :password %>
</p>
<p>
	<%= f.label :password_confirmation %>
</br>
	<%= f.password_field :password_confirmation %>
</p>
<%= f.submit "Reset Password and Log in" %>
<% end %>

app/views/users/show.html.erb
<p>
  <b>Email:</b>
  <%=h @user.email %>
</p>

<p>
  <b>Login count:</b>
  <%=h @user.login_count %>
</p>

<p>
  <b>Last request at:</b>
  <%=h @user.last_request_at %>
</p>

<p>
  <b>Last login at:</b>
  <%=h @user.last_login_at %>
</p>

<p>
  <b>Current login at:</b>
  <%=h @user.current_login_at %>
</p>

<p>
  <b>Last login ip:</b>
  <%=h @user.last_login_ip %>
</p>

<p>
  <b>Current login ip:</b>
  <%=h @user.current_login_ip %>
</p>

<%= link_to 'Logout', logout_path %>